### GENERAL SETTINGS ###

# Site settings
title: RHC Derby
description: "This is the Ramgarhia hockey club website."
analytics: 
baseurl: "" #important: start with /
url: "http://Rhc-derby.co.uk"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://www.facebook.com/rhcderby
    cssClass: facebook-official
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - City of Derby Academy
    - Farmhouse Rd
    - Derby
    - DE24 3AR
contact: Balraj Johal
email: tbd@rhc.com
tel: 01332 768758, 07753672537


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
coaches:
  - name: Raj Manku
    position: 2nd Level coach
    text: Level 2 qualified hockey coach who has coached for over 10 years.
    img: team01.jpg

homeWelcomeText: "Hello Guys, we need to fill this in with something useful. Let me know if you have any picutres that I can put in here"
